# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/instantnoodle/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),instantnoodle)

$(call add-radio-file-sha1-checked,radio/abl.img,63a2b7939e189985688b9819de14dadf82e510d6)
$(call add-radio-file-sha1-checked,radio/aop.img,326e4b02d442ece05bb56355a5515d1d33e7a6a8)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,ab220d37b571945d8816e792c44392dd78279fa4)
$(call add-radio-file-sha1-checked,radio/cmnlib.img,9ddb9a4758b6e89f4c257035aacd5c82b4ca2704)
$(call add-radio-file-sha1-checked,radio/cmnlib64.img,af5ac1eed4012f6138e427898333d5c22121bac3)
$(call add-radio-file-sha1-checked,radio/devcfg.img,72e96e6cc2338e5b3be530ff1697af56f9b134c7)
$(call add-radio-file-sha1-checked,radio/dsp.img,68845451b5e0e8eb823be435fa37eae9da6da351)
$(call add-radio-file-sha1-checked,radio/featenabler.img,542682acd52abcd4dd506bc7ea92f0e3b3f21bb4)
$(call add-radio-file-sha1-checked,radio/hyp.img,237be4f2279d505feb483d8f30abf2ecb155d156)
$(call add-radio-file-sha1-checked,radio/imagefv.img,55a50120fa297f2d846d8ced2722526217118fcb)
$(call add-radio-file-sha1-checked,radio/keymaster.img,c5bc2f192f1d7e00a48504f8a0cf94ffbd00d364)
$(call add-radio-file-sha1-checked,radio/logo.img,cef1d4886175660f305e78ab39b7782f8625e431)
$(call add-radio-file-sha1-checked,radio/modem.img,827608c64670e92a306422a86b7e330c5b324dd9)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,c70b312337398b23264412a7757146ea9dbbd0a7)
$(call add-radio-file-sha1-checked,radio/qupfw.img,01e7e718e043cc8967a02271d239056035c47c8f)
$(call add-radio-file-sha1-checked,radio/storsec.img,e5c7b7488620796dca78bdf788deb0d3af8fec6b)
$(call add-radio-file-sha1-checked,radio/tz.img,482df54d35aa4a5b0a91dd7936eb34651242af95)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,88357e33080fc30e360647aaf2225a7a7aaecb99)
$(call add-radio-file-sha1-checked,radio/xbl.img,6c2cc0c4000a15f0ce8d30e436626bba8039d8ce)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,41484f655c269964039925535f7f2c3a0e12edd0)

endif
