# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/instantnoodle/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),instantnoodle)

$(call add-radio-file-sha1-checked,radio/abl.img,ba8805893b1886e233d6423b3851a8f48cf20e5f)
$(call add-radio-file-sha1-checked,radio/aop.img,35005764dacae2512d6a08ff5cecd10a382e6806)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,80d0a104cc2c5de12268aa4d2c1f436938c9b03f)
$(call add-radio-file-sha1-checked,radio/cmnlib.img,26ab6eec6aa0a0126623120bc5506477d7937bac)
$(call add-radio-file-sha1-checked,radio/cmnlib64.img,ea362b5aece4f70e8490db38ced6c2023a27db42)
$(call add-radio-file-sha1-checked,radio/devcfg.img,27b20341c46e2a132d9d36e96b713f30eadfbb80)
$(call add-radio-file-sha1-checked,radio/dsp.img,68845451b5e0e8eb823be435fa37eae9da6da351)
$(call add-radio-file-sha1-checked,radio/featenabler.img,15c8593ae8bbce2940530ca8ca6aeeaa3d49d270)
$(call add-radio-file-sha1-checked,radio/hyp.img,2081acc554eb61b2ad99dc12097674bb04b8bc15)
$(call add-radio-file-sha1-checked,radio/imagefv.img,114953ff3e4886d6349fd4107972aa8ffe2cfdc0)
$(call add-radio-file-sha1-checked,radio/keymaster.img,706ed19304d27676499f5e3b746a136640671d56)
$(call add-radio-file-sha1-checked,radio/logo.img,cef1d4886175660f305e78ab39b7782f8625e431)
$(call add-radio-file-sha1-checked,radio/modem.img,180a47d517c58146b70a708a93bfa88e04b02f6d)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,aa0438d7b5cb582deb89e1e8908a2be2872351b1)
$(call add-radio-file-sha1-checked,radio/qupfw.img,1344c35ffc04be5265b61b448507cf9b12d94dab)
$(call add-radio-file-sha1-checked,radio/storsec.img,463f636ef7bc543aa9eaa3aabd2f9bb3f3a3fc23)
$(call add-radio-file-sha1-checked,radio/tz.img,3ec758942999ed5728637551828baeff4209e261)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,520362a1529713cc703b8944f7a3bfaf848411a6)
$(call add-radio-file-sha1-checked,radio/xbl.img,47bdb088b52b82d7dd6e652248c57614d2b813ad)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,bda1eb2f86d60946f4ce0bee25f319f8810b681d)

endif
